(function(){var h={},mt={},c={id:"bdfb0d7298c0c5a5a2475c291ac7aca2",dm:["exmail.qq.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'',ctrk:["%5b%22https%3a%5c%2f%5c%2fexmail.qq.com%5c%2fsignupfree%22%2c%22https%3a%5c%2f%5c%2fexmail.qq.com%22%2c%22https%3a%5c%2f%5c%2fexmail.qq.com%5c%2fportal%5c%2fproduct%5c%2fadvantages%22%2c%22https%3a%5c%2f%5c%2fexmail.qq.com%5c%2fportal%5c%2fproduct%5c%2ffunction%22%2c%22https%3a%5c%2f%5c%2fexmail.qq.com%5c%2fportal%5c%2fcharges%5c%2fbuyregister%22%2c%22https%3a%5c%2f%5c%2fexmail.qq.com%5c%2fportal%5c%2fuserstory%22%2c%22https%3a%5c%2f%5c%2fexmail.qq.com%5c%2flogin%22%2c%22https%3a%5c%2f%5c%2fexmail.qq.com%5c%2fcgi-bin%5c%2fbizmail_portal%3ft%3dbizmail_onlinesell%22%2c%22https%3a%5c%2f%5c%2fexmail.qq.com%5c%2fonlinesell%5c%2fintro%22%5d"],nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,oc:0,aet:'',hca:'43227E21C7AB984D',conv:0,med:0,cvcc:{id:/wpa|qq_kefu|launchBtn/i,q:/openqq|tencent:\/\/|qq\.(com|htm)/i},cvcf:['submitBtn'],apps:''};var s=void 0,u=!0,v=null,x=!1;mt.cookie={};mt.cookie.set=function(b,d,a){var p;a.R&&(p=new Date,p.setTime(p.getTime()+a.R));document.cookie=b+"="+d+(a.domain?"; domain="+a.domain:"")+(a.path?"; path="+a.path:"")+(p?"; expires="+p.toGMTString():"")+(a.Sc?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:v};
mt.cookie.tc=function(b,d){try{var a="Hm_ck_"+ +new Date;mt.cookie.set(a,"is-cookie-enabled",{domain:b,path:d,R:s});var p="is-cookie-enabled"===mt.cookie.get(a)?"1":"0";mt.cookie.set(a,"",{domain:b,path:d,R:-1});return p}catch(e){return"0"}};mt.lang={};mt.lang.d=function(b,d){return"[object "+d+"]"==={}.toString.call(b)};mt.lang.eb=function(b){return mt.lang.d(b,"Number")&&isFinite(b)};mt.lang.C=function(b){return mt.lang.d(b,"String")};mt.lang.isArray=function(b){return mt.lang.d(b,"Array")};
mt.lang.h=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.I=function(b,d){var a=x;if(b==v||!mt.lang.d(b,"Array")||d===s)return a;if(Array.prototype.indexOf)a=-1!==b.indexOf(d);else for(var p=0;p<b.length;p++)if(b[p]===d){a=u;break}return a};mt.lang.Ca=function(b,d){return isNaN(parseFloat(b))?0:parseFloat(parseFloat(b).toFixed(d))};mt.url={};
mt.url.m=function(b,d){var a=b.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return a?a[3]:v};mt.url.Nc=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:v};mt.url.Wb=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):v};mt.url.O=function(b){return(b=mt.url.Wb(b))?b.replace(/:\d+$/,""):b};mt.url.Fa=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):v};
(function(){var b=mt.lang,d=mt.url;mt.g={};mt.g.Va=function(a){return document.getElementById(a)};mt.g.Da=function(a){if(!a)return v;try{a=String(a);if(0===a.indexOf("!HMCQ!"))return a;if(0===a.indexOf("!HMCC!"))return document.querySelector(a.substring(6,a.length));for(var b=a.split(">"),e=document.body,d=b.length-1;0<=d;d--)if(-1<b[d].indexOf("#")){var f=b[d].split("#")[1];(e=document.getElementById(f))||(e=document.getElementById(decodeURIComponent(f)));b=b.splice(d+1,b.length-(d+1));break}for(a=
0;e&&a<b.length;){var m=String(b[a]).toLowerCase();if(!("html"===m||"body"===m)){var d=0,q=b[a].match(/\[(\d+)\]/i),f=[];if(q)d=q[1]-1,m=m.split("[")[0];else if(1!==e.childNodes.length){for(var r=0,t=0,n=e.childNodes.length;t<n;t++){var g=e.childNodes[t];1===g.nodeType&&g.nodeName.toLowerCase()===m&&r++;if(1<r)return v}if(1!==r)return v}for(r=0;r<e.childNodes.length;r++)1===e.childNodes[r].nodeType&&e.childNodes[r].nodeName.toLowerCase()===m&&f.push(e.childNodes[r]);if(!f[d])return v;e=f[d]}a++}return e}catch(l){return v}};
mt.g.Fa=function(a,b){var e=[],d=[];if(!a)return d;for(;a.parentNode!=v;){for(var f=0,m=0,q=a.parentNode.childNodes.length,r=0;r<q;r++){var t=a.parentNode.childNodes[r];if(t.nodeName===a.nodeName&&(f++,t===a&&(m=f),0<m&&1<f))break}if((q=""!==a.id)&&b){e.unshift("#"+encodeURIComponent(a.id));break}else q&&(q="#"+encodeURIComponent(a.id),q=0<e.length?q+">"+e.join(">"):q,d.push(q)),e.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<f?"["+m+"]":""));a=a.parentNode}d.push(e.join(">"));return d};
mt.g.la=function(a){return(a=mt.g.Fa(a,u))&&a.length?String(a[0]):""};mt.g.$b=function(a){return mt.g.Fa(a,x)};mt.g.Wa=function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return v};mt.g.Sb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.g.Xa=function(a){var b={top:0,left:0};if(!a)return b;var e=mt.g.Sb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());return{top:b.top+(window.pageYOffset||e.scrollTop)-
(e.clientTop||0),left:b.left+(window.pageXOffset||e.scrollLeft)-(e.clientLeft||0)}};mt.g.getAttribute=function(a,b){var e=a.getAttribute&&a.getAttribute(b)||v;if(!e&&a.attributes&&a.attributes.length)for(var d=a.attributes,f=d.length,m=0;m<f;m++)d[m].nodeName===b&&(e=d[m].nodeValue);return e};mt.g.V=function(a){var b="document";a.tagName!==s&&(b=a.tagName);return b.toLowerCase()};mt.g.ec=function(a){var d="";a.textContent?d=b.trim(a.textContent):a.innerText&&(d=b.trim(a.innerText));d&&(d=d.replace(/\s+/g,
" ").substring(0,255));return d};mt.g.U=function(a,p){var e;b.C(a)&&0===String(a).indexOf("!HMCQ!")?(e=String(a),e=d.m(document.location.href,e.substring(6,e.length))):b.C(a)||(e=mt.g.V(a),"input"===e&&p&&("button"===a.type||"submit"===a.type)?e=b.trim(a.value)||"":"input"===e&&!p&&"password"!==a.type?e=b.trim(a.value)||"":"img"===e?(e=mt.g.getAttribute,e=e(a,"alt")||e(a,"title")||e(a,"src")):e="body"===e||"html"===e?["(hm-default-content-for-",e,")"].join(""):mt.g.ec(a));return String(e||"").substring(0,
255)};(function(){(mt.g.lb=function(){function b(){if(!b.oa){b.oa=u;for(var d=0,e=k.length;d<e;d++)k[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(d,1);return}b()}var e=x,k=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,x);b()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),b())});(function(){if(!e)if(e=u,"complete"===document.readyState)b.oa=u;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,x),window.addEventListener("load",b,x);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",b);var m=x;try{m=window.frameElement==v}catch(q){}document.documentElement.doScroll&&m&&d()}})();return function(d){b.oa?d():k.push(d)}}()).oa=x})();return mt.g})();mt.event={};
mt.event.e=function(b,d,a){b.attachEvent?b.attachEvent("on"+d,function(d){a.call(b,d)}):b.addEventListener&&b.addEventListener(d,a,x)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=x};
(function(){var b=mt.event;mt.f={};mt.f.ma=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.f.Xb=function(){if(document.documentMode)return document.documentMode;var b=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return b?+b[1]||0:0};mt.f.Pc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(b){return x}};mt.f.cookieEnabled=navigator.cookieEnabled;mt.f.javaEnabled=navigator.javaEnabled();
mt.f.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.f.yc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.f.colorDepth=window.screen.colorDepth||0;mt.f.bc=function(){var b;b=b||document;return parseInt(window.pageYOffset||b.documentElement.scrollTop||b.body&&b.body.scrollTop||0,10)};mt.f.ab=function(){var b=document;return parseInt(window.innerHeight||b.documentElement.clientHeight||b.body&&b.body.clientHeight||0,10)};mt.f.H=
function(){return mt.f.bc()+mt.f.ab()};mt.f.ub=0;mt.f.gc=function(){var b=document;return parseInt(window.innerWidth||b.documentElement.clientWidth||b.body.offsetWidth||0,10)};mt.f.orientation=0;(function(){function d(){var b=0;window.orientation!==s&&(b=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==s)&&(b=screen.orientation.angle);mt.f.orientation=b;mt.f.ub=mt.f.gc()}d();b.e(window,"orientationchange",d)})();return mt.f})();mt.A={};
mt.A.parse=function(b){return(new Function("return ("+b+")"))()};
mt.A.stringify=function(){function b(b){/["\\\x00-\x1f]/.test(b)&&(b=b.replace(/["\\\x00-\x1f]/g,function(b){var d=a[b];if(d)return d;d=b.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+b+'"'}function d(b){return 10>b?"0"+b:b}var a={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(a){switch(typeof a){case "undefined":return"undefined";case "number":return isFinite(a)?String(a):"null";case "string":return b(a);case "boolean":return String(a);
default:if(a===v)return"null";if(a instanceof Array){var e=["["],k=a.length,f,m,q;for(m=0;m<k;m++)switch(q=a[m],typeof q){case "undefined":case "function":case "unknown":break;default:f&&e.push(","),e.push(mt.A.stringify(q)),f=1}e.push("]");return e.join("")}if(a instanceof Date)return'"'+a.getFullYear()+"-"+d(a.getMonth()+1)+"-"+d(a.getDate())+"T"+d(a.getHours())+":"+d(a.getMinutes())+":"+d(a.getSeconds())+'"';f=["{"];m=mt.A.stringify;for(k in a)if(Object.prototype.hasOwnProperty.call(a,k))switch(q=
a[k],typeof q){case "undefined":case "unknown":case "function":break;default:e&&f.push(","),e=1,f.push(m(k)+":"+m(q))}f.push("}");return f.join("")}}}();mt.localStorage={};mt.localStorage.wa=function(){if(!mt.localStorage.j)try{mt.localStorage.j=document.createElement("input"),mt.localStorage.j.type="hidden",mt.localStorage.j.style.display="none",mt.localStorage.j.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.j)}catch(b){return x}return u};
mt.localStorage.set=function(b,d,a){var p=new Date;p.setTime(p.getTime()+a||31536E6);try{window.localStorage?(d=p.getTime()+"|"+d,window.localStorage.setItem(b,d)):mt.localStorage.wa()&&(mt.localStorage.j.expires=p.toUTCString(),mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.setAttribute(b,d),mt.localStorage.j.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var d=b.indexOf("|"),a=b.substring(0,d)-0;if(a&&a>(new Date).getTime())return b.substring(d+1)}}else if(mt.localStorage.wa())try{return mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.getAttribute(b)}catch(p){}return v};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.wa())try{mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.removeAttribute(b),mt.localStorage.j.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,d){try{window.sessionStorage&&window.sessionStorage.setItem(b,d)}catch(a){}};
mt.sessionStorage.get=function(b){try{return window.sessionStorage?window.sessionStorage.getItem(b):v}catch(d){return v}};mt.sessionStorage.remove=function(b){try{window.sessionStorage&&window.sessionStorage.removeItem(b)}catch(d){}};mt.qb={};mt.qb.log=function(b,d){var a=new Image,p="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[p]=a;a.onload=function(){a.onload=v;a=window[p]=v;d&&d(b)};a.src=b};mt.Ma={};
mt.Ma.fc=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(b=d.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=d.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(a){}return b};
mt.Ma.Mc=function(b,d,a,p,e){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+a+'" height="'+p+'"><param name="movie" value="'+d+'" /><param name="flashvars" value="'+(e||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+a+'" height="'+p+'" src="'+d+'" flashvars="'+(e||"")+'" allowscriptaccess="always" /></object>'};
h.B={Oc:"http://tongji.baidu.com/hm-web/welcome/ico",La:"hm.baidu.com/hm.gif",Bb:/^(tongji|hmcdn).baidu.com$/,tb:"tongji.baidu.com",kc:"hmmd",lc:"hmpl",Jc:"utm_medium",jc:"hmkw",Lc:"utm_term",hc:"hmci",Ic:"utm_content",mc:"hmsr",Kc:"utm_source",ic:"hmcu",Hc:"utm_campaign",P:0,L:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",qa:"https:",Qc:0,Hb:6E5,Rc:6E5,zc:5E3,Ib:5,Q:1024,Gb:1,ba:2147483647,rb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn r ww p ct u tt".split(" "),
X:u,Sa:["a","input","button"],Pa:{id:"data-hm-id",ga:"data-hm-class",fa:"data-hm-xpath",content:"data-hm-content",ta:"data-hm-tag",link:"data-hm-link"},Ra:"data-hm-enabled",Qa:"data-hm-disabled",vc:"https://hmcdn.baidu.com/static/tongji/plugins/",jb:["UrlChangeTracker","OcpcCbHm"]};(function(){var b={G:{},e:function(b,a){this.G[b]=this.G[b]||[];this.G[b].push(a)},M:function(b,a){this.G[b]=this.G[b]||[];for(var p=this.G[b].length,e=0;e<p;e++)this.G[b][e](a)}};return h.w=b})();
(function(){var b=mt.lang,d=/^https?:\/\//,a={Rb:function(b){var a;try{a=JSON.parse(decodeURIComponent(b[0]))}catch(d){}return a},fb:function(b,a){var k=h.c&&h.c.b&&h.c.b.u||document.location.href;d.test(b)||(k=k.replace(d,""));b=b.replace(/\/$/,"");k=k.replace(/\/$/,"");a&&(k=k.replace(/^(https?:\/\/)?www\./,"$1"));return RegExp("^"+b.replace(/[?.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(k)},S:function(d,e){var k=a.Rb(d);if(!b.d(k,"Undefined")){if(b.d(k,"Array")){for(var f=0;f<k.length;f++)if(a.fb(k[f],
e))return u;return x}if(b.d(k,"Object")){var f=[],m;for(m in k)k.hasOwnProperty(m)&&a.fb(m,e)&&(f=f.concat(k[m]));return f}}}};return h.ha=a})();
(function(){function b(b,p){var e=document.createElement("script");e.charset="utf-8";d.d(p,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=v,p()}:e.onload=function(){p()});e.src=b;var k=document.getElementsByTagName("script")[0];k.parentNode.insertBefore(e,k)}var d=mt.lang;return h.load=b})();
(function(){var b=mt.cookie,d=mt.localStorage,a=mt.sessionStorage,p={getData:function(e){try{return b.get(e)||a.get(e)||d.get(e)}catch(k){}},setData:function(e,k,f){try{b.set(e,k,{domain:p.T(),path:p.ka(),R:f}),f?d.set(e,k,f):a.set(e,k)}catch(m){}},removeData:function(e){try{b.set(e,"",{domain:p.T(),path:p.ka(),R:-1}),a.remove(e),d.remove(e)}catch(k){}},Y:function(b,a){b="."+b.replace(/:\d+/,"");a="."+a.replace(/:\d+/,"");var d=b.indexOf(a);return-1<d&&d+a.length===b.length},pa:function(b,a){b=b.replace(/^https?:\/\//,
"");return 0===b.indexOf(a)},T:function(){for(var b=document.location.hostname,a=0,d=c.dm.length;a<d;a++)if(p.Y(b,c.dm[a]))return c.dm[a].replace(/(:\d+)?[/?#].*/,"");return b},ka:function(){for(var b=0,a=c.dm.length;b<a;b++){var d=c.dm[b];if(-1<d.indexOf("/")&&p.pa(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.za=p})();
(function(){var b=mt.lang,d=mt.A,a=h.za,p={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},e={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},k=["session","user"],f="Hm_up_"+c.id,m={init:function(){m.qc()},qc:function(){try{var e=d.parse(decodeURIComponent(a.getData(f)));b.d(e,"Object")&&(p.user=e)}catch(r){}},z:function(b){var a={};p[b]!==s&&(a=p[b]);b=this.$a();for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b},$a:function(){for(var b={},a,d=k.length-
1;0<=d;d--){a=p[k[d]];for(var n in a)a.hasOwnProperty(n)&&(b[n]=a[n])}return b},setProperty:function(a,e,f){var n=p[a];if(b.d(n,"Object")&&b.d(e,"Object")){for(var g in e)if(e.hasOwnProperty(g)){var l=b.h(String(g));if(f||!/^_/.test(l)&&!/_$/.test(l)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(l)){var y=e[g];if(y==v)delete n[l];else{if(b.d(y,"Object")||b.d(y,"Array"))y=d.stringify(y);y=b.h(String(y));m.sc(a,l,y)&&(n[l]={value:y,scope:m.Za(a)})}}}"user"===a&&m.Ja()}},o:function(a){a!==s&&("userId"===
a&&b.d(p.user,"Object")?(delete p.user.uid_,m.Ja()):"user"===a&&b.d(p.user,"Object")?(a=p.user.uid_,p.user=a===s?{}:{uid_:a},m.Ja()):p[a]!==s&&(p[a]={}))},Ja:function(){try{a.setData(f,encodeURIComponent(d.stringify(p.user)),c.age)}catch(b){}},sc:function(b,a,d){var e=u,g=p[b];if(256<encodeURIComponent(String(a)).length||256<encodeURIComponent(String(d)).length)e=x;else{var l=g[a];g[a]={value:d,scope:m.Za(b)};b=m.K(m.z(b));2048<encodeURIComponent(b).length&&(l!==s?g[a]=l:delete g[a],e=x)}return e},
K:function(b){var a=[],d,e;for(e in b)b.hasOwnProperty(e)&&(d=[e,b[e].value],(1===b[e].scope||2===b[e].scope)&&d.push(b[e].scope),a.push(d.join("*")));return a.join("!")},Za:function(b){b=e[b];return b!==s?b:e.others}};return h.N=m})();
(function(){var b=mt.g,d=mt.lang,a=h.w,p=h.ha,e=h.N,k=e.K;if(d.isArray(c.cptrk)&&0<c.cptrk.length){var f={ib:{},ua:{},init:function(){for(var b,a=p.S(c.cptrk)||[],e=0;e<a.length;e++)if(b=a[e],b.a!==s&&d.d(b.a,"Object")){b=b.a;for(var k in b)b.hasOwnProperty(k)&&(f.ua[k]=String(b[k]))}},hb:function(){var a,d,e;for(e in f.ua)if(f.ua.hasOwnProperty(e)&&f.ib[e]===s&&(a=f.ua[e],a=b.Da(a)))d=d===s?{}:d,d[e]=b.U(a,x),f.ib[e]=u;return d},Ga:function(){var b=f.hb();b&&f.Bc(b)},pc:function(){"MutationObserver"in
window&&document.body?(new MutationObserver(f.Ga)).observe(document.body,{childList:u,subtree:u}):window.setInterval(f.Ga,15E3)},Bc:function(b){if(d.d(b,"Object")){e.setProperty("pageview",b);b=h.c.b.p;var a=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=k(e.z("pageview"));h.c.i();h.c.b.p=b;h.c.b.ep=a;e.o("pageview")}}};f.init();a.e("pv-b",function(){var b=f.hb();b&&e.setProperty("pageview",b)});f.pc();b.lb(f.Ga)}})();
(function(){var b=mt.lang,d=mt.g,a=h.ha,p={ia:function(b,k){return function(f){var m=f.target||f.srcElement;if(m){var q=a.S(k)||[],r=m.getAttribute(b.va);f=f.clientX+":"+f.clientY;if(r&&r===f)m.removeAttribute(b.va);else if(0<q.length&&(m=d.$b(m))&&m.length)if(q=m.length,r=m[m.length-1],1E4>q*r.split(">").length)for(r=0;r<q;r++)p.pb(b,m[r]);else p.pb(b,r)}}},pb:function(a,d){for(var f={},m=String(d).split(">").length,q=0;q<m;q++)f[d]="",d=d.substring(0,d.lastIndexOf(">"));a&&(b.d(a,"Object")&&a.Ta)&&
a.Ta(f)},xc:function(b,a){return function(d){(d.target||d.srcElement).setAttribute(b.va,d.clientX+":"+d.clientY);b&&b.s&&(a?b.s(a):b.s("#"+encodeURIComponent(this.id),d.type))}}};return h.Ba=p})();
(function(){var b=mt.g,d=mt.event,a=mt.lang,p=h.B,e=h.ha,k=h.Ba,f=h.N,m=f.K,q={va:"HM_ce",wb:function(){if(c.cetrk&&0<c.cetrk.length){d.e(document,"click",k.ia(q,c.cetrk));for(var a=e.S(c.cetrk)||[],f=0,n=a.length;f<n;f++){var g=a[f],l=g.p||"";-1===l.indexOf(">")&&(0===l.indexOf("#")&&(l=l.substring(1)),(l=b.Va(l))&&d.e(l,"click",k.xc(q,g)))}}},Ta:function(b){for(var a=e.S(c.cetrk)||[],d=0;d<a.length;d++){var g=a[d],l=q.Ub(g.p,b);l&&q.s(g,l)}},Ub:function(b,a){b=String(b);if(0<b.indexOf("*")){var d=
RegExp("^"+b.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),g;for(g in a)if(a.hasOwnProperty(g)&&d.test(g))return g;return v}return a.hasOwnProperty(b)?b:v},s:function(d,e){h.c.b.et=7;var n=d&&d.k||"",n=a.h(n),g={};if(d&&d.a&&a.d(d.a,"Object")){var l=d.a,y;for(y in l)if(l.hasOwnProperty(y)){var w=q.ac(l[y]||"",e),w=w?b.U(w,x):"";g[y]=w}}g=q.Pb(g,e||d&&d.p);g._iden=n;f.setProperty("customEvent",g);h.c.b.ep="";h.c.b.p=m(f.z("customEvent"));h.c.i();h.c.b.p="";f.o("customEvent")},
Pb:function(a,d){var e=b.Da(d),g=p.Pa;e&&(c.aet&&c.aet.length?(a.ei_=b.getAttribute(e,g.id)||b.getAttribute(e,"id")||"",a.ec_=b.getAttribute(e,g.ga)||b.getAttribute(e,"class")||"",a.ex_=b.getAttribute(e,g.fa)||b.la(e),a.en_=b.getAttribute(e,g.content)||b.U(e,u),a.et_=b.getAttribute(e,g.ta)||b.V(e),a.el_=b.getAttribute(e,g.link)||b.getAttribute(e,"href")||""):(a.ex_=b.getAttribute(e,g.fa)||b.la(e),a.en_=b.getAttribute(e,g.content)||b.U(e,u)));return a},ac:function(a,d){a=String(a);d=String(d);if(0<
a.indexOf("*")){var e=/.*\[(\d+)\]$/.exec(d);a=a.replace("*",e?e[1]:"1")}return b.Da(a)}};h.w.e("pv-b",q.wb);return q})();
(function(){var b=mt.g,d=mt.lang,a=mt.event,p=mt.f,e=h.B,k=h.ha,f=[],m={vb:function(){c.ctrk&&0<c.ctrk.length&&(a.e(document,"mouseup",m.Fb()),a.e(window,"unload",function(){m.ra()}),setInterval(function(){m.ra()},e.Hb))},Fb:function(){return function(b){if(k.S(c.ctrk,u)&&(b=m.Qb(b),""!==b)){var a=(e.qa+"//"+e.La+"?"+h.c.ob().replace(/ep=[^&]*/,"ep="+encodeURIComponent(b))).length;a+(e.ba+"").length>e.Q||(a+encodeURIComponent(f.join("!")+(f.length?"!":"")).length+(e.ba+"").length>e.Q&&m.ra(),f.push(b),
(f.length>=e.Ib||/\*a\*/.test(b))&&m.ra())}}},Qb:function(a){var f=a.target||a.srcElement;if(0===e.Gb){var k=(f.tagName||"").toLowerCase();if("embed"==k||"object"==k)return""}var n;p.ma?(n=Math.max(document.documentElement.scrollTop,document.body.scrollTop),k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),k=a.clientX+k,n=a.clientY+n):(k=a.pageX,n=a.pageY);a=m.Yb(a,f,k,n);var g=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:k-=
g/2;break;case 2:k-=g}g=[];g.push(k);g.push(n);g.push(a.aa);g.push(a.ca);g.push(a.wc);g.push(d.h(a.uc));g.push(a.ea);g.push(a.W);(f="a"===(f.tagName||"").toLowerCase()?f:b.Wa(f))?(g.push("a"),g.push(d.h(encodeURIComponent(f.href)))):g.push("b");return g.join("*")},Yb:function(a,e,f,n){a=b.la(e);var g=0,l=0,y=0,w=0;if(e&&(g=e.offsetWidth||e.clientWidth,l=e.offsetHeight||e.clientHeight,w=b.Xa(e),y=w.left,w=w.top,d.d(e.getBBox,"Function")&&(l=e.getBBox(),g=l.width,l=l.height),"html"===(e.tagName||"").toLowerCase()))g=
Math.max(g,e.clientWidth),l=Math.max(l,e.clientHeight);return{aa:Math.round(100*((f-y)/g)),ca:Math.round(100*((n-w)/l)),wc:p.orientation,uc:a,ea:g,W:l}},ra:function(){0!==f.length&&(h.c.b.et=2,h.c.b.ep=f.join("!"),h.c.i(),f=[])}};h.w.e("pv-b",m.vb);return m})();
(function(){var b=mt.lang,d=mt.g,a=mt.event,p=mt.f,e=h.B,k=h.w,f=h.N,m=f.K,q=+new Date,r=[],t={ia:function(){return function(a){if(h.c&&h.c.X&&c.aet&&c.aet.length){var g=a.target||a.srcElement;if(g){var l=h.c.Sa,f=d.getAttribute(g,e.Ra)!=v?u:x;if(d.getAttribute(g,e.Qa)==v)if(f)t.xa(t.Ea(g,a));else{var w=d.V(g);if(b.I(l,"*")||b.I(l,w))t.xa(t.Ea(g,a));else for(;g.parentNode!=v;){var f=g.parentNode,w=d.V(f),A="a"===w&&b.I(l,"a")?u:x,w="button"===w&&b.I(l,"button")?u:x,z=d.getAttribute(f,e.Ra)!=v?u:x;
if(d.getAttribute(f,e.Qa)==v&&(A||w||z)){t.xa(t.Ea(f,a));break}g=g.parentNode}}}}}},Ea:function(a,g){var l={},f=e.Pa;l.id=d.getAttribute(a,f.id)||d.getAttribute(a,"id")||"";l.ga=d.getAttribute(a,f.ga)||d.getAttribute(a,"class")||"";l.fa=d.getAttribute(a,f.fa)||d.la(a);l.content=d.getAttribute(a,f.content)||d.U(a,u);l.ta=d.getAttribute(a,f.ta)||d.V(a);l.link=d.getAttribute(a,f.link)||d.getAttribute(a,"href")||"";l.type=g.type||"click";f=b.eb(a.offsetTop)?a.offsetTop:0;"click"===g.type?f=p.ma?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.gb&&g.gb.changedTouches)&&(f=g.gb.changedTouches[0].pageY);l.Gc=f;f=this.Tb(g);l.aa=f.aa||0;l.ca=f.ca||0;l.ea=f.ea||0;l.W=f.W||0;l.Na=f.Na||"b";return l},Tb:function(a){var g=a.target||a.srcElement,e;if(p.ma){var f=Math.max(document.documentElement.scrollTop,document.body.scrollTop);e=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);e=a.clientX+e;a=a.clientY+f}else e=a.pageX,
a=a.pageY;var w=f=0,A=0,z=0;if(g&&(f=g.offsetWidth||g.clientWidth,w=g.offsetHeight||g.clientHeight,z=d.Xa(g),A=z.left,z=z.top,b.d(g.getBBox,"Function")&&(w=g.getBBox(),f=w.width,w=w.height),"html"===(g.tagName||"").toLowerCase()))f=Math.max(f,g.clientWidth),w=Math.max(w,g.clientHeight);return{aa:Math.round(100*((e-A)/f)),ca:Math.round(100*((a-z)/w)),ea:f,W:w,Na:("a"===(g.tagName||"").toLowerCase()?g:d.Wa(g))?"a":"b"}},xa:function(a){var g=b.h;a=[+new Date-(h.c.Z!==s?h.c.Z:q),g(a.id),g(a.ga),g(a.ta),
g(a.fa),g(a.link),g(a.content),a.type,a.Gc,a.aa,a.ca,a.ea,a.W,a.Na].join("*");t.ya(a);b.d(this.da(),"Function")&&this.da()()},ya:function(a){a.length>e.Q||(encodeURIComponent(r.join("!")+a).length>e.Q&&(t.s(r.join("!")),r=[]),r.push(a))},s:function(a){h.c.b.et=5;h.c.b.ep=a;f.setProperty("autoEventTracking",{view_h_:p.H()},u);h.c.b.p=m(f.z("autoEventTracking"));h.c.i();h.c.b.p="";f.setProperty("autoEventTracking",{view_h_:v},u)},da:function(){return function(){r&&r.length&&(t.s(r.join("!")),r=[])}}};
b.C(c.aet)&&""!==c.aet&&k.e("pv-b",function(){a.e(document,"click",t.ia());"ontouchend"in document&&a.e(window,"touchend",t.ia());a.e(window,"unload",t.da())});return t})();
(function(){var b=mt.lang,d=mt.event,a=mt.f,p=h.B,e=h.w,k=h.N,f=k.K,m=+new Date,q=[],r=v,t={zb:function(){b.C(c.aet)&&""!==c.aet&&setInterval(t.nb,p.zc)},nb:function(){var b=a.H();0<b-h.c.b.vl&&(h.c.b.vl=b)}},n={Lb:function(){return function(){h.c&&(h.c.X&&c.aet&&c.aet.length)&&(window.clearTimeout(r),r=window.setTimeout(function(){n.yb(a.H())},150))}},yb:function(a){n.ya([+new Date-(h.c.Z!==s?h.c.Z:m),a].join("*"))},ya:function(a){if(encodeURIComponent(q.join("!")+a).length>p.Q||3<q.length)n.s(q.join("!")),
q=[];q.push(a)},s:function(b){t.nb();h.c.b.et=6;h.c.b.vh=a.ab();h.c.b.ep=b;k.setProperty("autoEventTracking",{view_h_:a.H()},u);h.c.b.p=f(k.z("autoEventTracking"));h.c.i();h.c.b.p="";k.setProperty("autoEventTracking",{view_h_:v},u)},da:function(){return function(){q&&q.length&&(n.s(q.join("!")),q=[])}}};b.C(c.aet)&&""!==c.aet&&e.e("pv-b",function(){d.e(window,"scroll",n.Lb());d.e(window,"unload",n.da());t.zb()});return n})();
(function(){function b(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.Aa.Zb()+","+h.Aa.Vb();h.c.b.hca=c.hca;h.c.i()}}function d(){clearTimeout(A);var a;y&&(a="visible"==document[y]);w&&(a=!document[w]);m="undefined"==typeof a?u:a;if((!f||!q)&&m&&r)l=u,n=+new Date;else if(f&&q&&(!m||!r))l=x,g+=+new Date-n;f=m;q=r;A=setTimeout(d,100)}function a(a){var b=document,g="";if(a in b)g=a;else for(var d=["webkit","ms","moz","o"],e=0;e<d.length;e++){var l=d[e]+a.charAt(0).toUpperCase()+a.slice(1);
if(l in b){g=l;break}}return g}function p(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))r="focus"==a.type||"focusin"==a.type?u:x,d()}var e=mt.event,k=h.w,f=u,m=u,q=u,r=u,t=+new Date,n=t,g=0,l=u,y=a("visibilityState"),w=a("hidden"),A;d();(function(){var a=y.replace(/[vV]isibilityState/,"visibilitychange");e.e(document,a,d);e.e(window,"pageshow",d);e.e(window,"pagehide",d);"object"==typeof document.onfocusin?(e.e(document,"focusin",p),e.e(document,"focusout",p)):(e.e(window,
"focus",p),e.e(window,"blur",p))})();h.Aa={Zb:function(){return+new Date-t},Vb:function(){return l?+new Date-n+g:g}};k.e("pv-b",function(){e.e(window,"unload",b())});k.e("duration-send",b());k.e("duration-done",function(){n=t=+new Date;g=0});return h.Aa})();
(function(){var b=mt.lang,d=h.B,a=h.load,p={nc:function(e){if((window._dxt===s||b.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var k=h.c.T();a([d.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(k)].join(""),e)}},Fc:function(a){if(b.d(a,"String")||b.d(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Jb=p})();
(function(){function b(a,b,d,e){if(!(a===s||b===s||e===s)){if(""===a)return[b,d,e].join("*");a=String(a).split("!");for(var f,z=x,k=0;k<a.length;k++)if(f=a[k].split("*"),String(b)===f[0]){f[1]=d;f[2]=e;a[k]=f.join("*");z=u;break}z||a.push([b,d,e].join("*"));return a.join("!")}}var d=mt.url,a=mt.lang,p=mt.f,e=h.B,k=h.w,f=h.Jb,m=h.load,q=h.za,r=h.N,t=r.K,n={$:[],sa:0,Ia:x,F:{Oa:"",page:""},init:function(){n.l=0;r.init();k.e("pv-b",function(){n.Kb();n.Mb()});k.e("pv-d",function(){n.Nb();n.F.page=""});
k.e("stag-b",function(){h.c.b.api=n.l||n.sa?n.l+"_"+n.sa:"";h.c.b.ct=[decodeURIComponent(q.getData("Hm_ct_"+c.id)||""),n.F.Oa,n.F.page].join("!")});k.e("stag-d",function(){h.c.b.api=0;n.l=0;n.sa=0})},Kb:function(){var b=window._hmt||[];if(!b||a.d(b,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var b=window._hmt,g=0;g<arguments.length;g++){var d=arguments[g];a.d(d,"Array")&&(b.cmd[b.id].push(d),"_setAccount"===d[0]&&(1<d.length&&/^[0-9a-f]{31,32}$/.test(d[1]))&&(d=d[1],b.id=d,b.cmd[d]=b.cmd[d]||
[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,b)},Mb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order)$/,e=0,f=b.length;e<f;e++){var z=b[e];d.test(z[0])?n.$.push(z):n.Ka(z)}a.cmd[c.id]={push:n.Ka}},Nb:function(){if(0<n.$.length)for(var a=0,b=n.$.length;a<b;a++)n.Ka(n.$[a]);n.$=v},Ka:function(b){var d=b[0];if(n.hasOwnProperty(d)&&a.d(n[d],"Function"))n[d](b)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{31,32}$/.test(a[1])&&
(n.l|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],x===a||u===a))n.l|=2,h.c.bb=a},_trackPageview:function(a){1<a.length&&(a[1].charAt&&"/"===a[1].charAt(0))&&(n.l|=4,h.c.b.sn=h.c.Ya(),h.c.b.et=0,h.c.b.ep="",h.c.b.vl=p.H(),h.c.b.kb=0,h.c.Ha?(h.c.b.nv=0,h.c.b.st=4):h.c.Ha=u,n.Ia||(h.c.b.su=h.c.b.u||document.location.href),h.c.b.u=e.protocol+"//"+document.location.host+a[1],h.c.b.p=t(r.z("pageview")),h.c.i(),h.c.b.p="",h.c.Z=+new Date,r.o("pageview"))},_trackEvent:function(b){2<b.length&&
(n.l|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=a.h(b[1])+"*"+a.h(b[2])+(b[3]?"*"+a.h(b[3]):"")+(b[4]?"*"+a.h(b[4]):""),h.c.b.p=t(r.$a()),h.c.i(),h.c.b.p="")},_setCustomVar:function(b){if(!(4>b.length)){var d=b[1],e=b[4]||3;if(0<d&&6>d&&0<e&&4>e){n.sa++;for(var f=(h.c.b.cv||"*").split("!"),A=f.length;A<d-1;A++)f.push("*");f[d-1]=e+"*"+a.h(b[2])+"*"+a.h(b[3]);h.c.b.cv=f.join("!");b=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==b?q.setData("Hm_cv_"+c.id,encodeURIComponent(b),
c.age):q.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(d){if(!(3>d.length)){var e=a.h(d[1]);d=a.h(d[2]);if(e!==s&&d!==s){var f=decodeURIComponent(q.getData("Hm_ct_"+c.id)||""),f=b(f,e,1,d);q.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(d){if(!(3>d.length)){var e=a.h(d[1]);d=a.h(d[2]);if(e!==s&&d!==s){var f=n.F.Oa,f=b(f,e,2,d);n.F.Oa=f}}},_setPageTag:function(d){if(!(3>d.length)){var e=a.h(d[1]);d=a.h(d[2]);if(e!==s&&d!==s){var f=n.F.page,f=b(f,e,3,d);n.F.page=f}}},
_setReferrerOverride:function(b){1<b.length&&(b=b[1],a.d(b,"String")?(h.c.b.su="/"===b.charAt(0)?e.protocol+"//"+window.location.host+b:b,n.Ia=u):n.Ia=x)},_trackOrder:function(b){var d=b[1];if(a.d(d,"Object")&&a.C(d.orderId)){window._hmt=window._hmt||[];b=d.orderId;var e=a.Ca(d.orderTotal,2);r.setProperty("customEvent",{order_id_:b,order_total_:e},u);window._hmt.push(["_trackCustomEvent","order_",{}]);r.o("customEvent");for(var d=d.item||[],f,A,z,k=0;k<d.length;k++)f=d[k],A=a.Ca(f.Price,2),z=a.Ca(f.Quantity,
0),r.setProperty("customEvent",{order_id_:b,order_total_:e,product_id_:f.skuId||"",product_name_:f.skuName||"",product_category_:f.category||"",product_price_:A,product_quantity_:z,product_amount_:A*z},u),window._hmt.push(["_trackCustomEvent","product_",{}]),r.o("customEvent")}},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])n.l|=32,h.c.b.et=93,h.c.b.ep=a,h.c.i()},_setDataxId:function(a){a=a[1];f.nc();f.Fc(a)},_setUserId:function(b){b=b[1];if(b!==s&&(a.C(b)||a.eb(b))){var d=
r.z("user").uid_;if(!(d&&d.value===a.h(String(b)))){var d=h.c.b.p,e=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+a.h(String(b));h.c.i();var f={};f.uid_=b;r.setProperty("user",f,u);h.c.b.p=d;h.c.b.ep=e}}},_clearUserId:function(a){1<a.length&&u===a[1]&&r.o("userId")},_setUserProperty:function(b){b=b[1];a.d(b,"Object")&&r.setProperty("user",b)},_clearUserProperty:function(a){1<a.length&&u===a[1]&&r.o("user")},_setSessionProperty:function(b){b=b[1];a.d(b,"Object")&&r.setProperty("session",b)},_clearSessionProperty:function(a){1<
a.length&&u===a[1]&&r.o("session")},_setPageviewProperty:function(b){b=b[1];a.d(b,"Object")&&r.setProperty("pageview",b)},_clearPageviewProperty:function(a){1<a.length&&u===a[1]&&r.o("pageview")},_setAutoEventTrackingProperty:function(b){b=b[1];a.d(b,"Object")&&r.setProperty("autoEventTracking",b)},_clearAutoEventTrackingProperty:function(a){1<a.length&&u===a[1]&&r.o("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],x===a||u===a))h.c.cb=a},_setAutoEventTracking:function(a){if(1<
a.length&&(a=a[1],x===a||u===a))h.c.X=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.i())):k.M("duration-send");k.M("duration-done")},_require:function(a){1<a.length&&(a=a[1],e.Bb.test(d.O(a))&&m(a))},_providePlugin:function(b){if(1<b.length){var d=window._hmt,f=b[1];b=b[2];if(a.I(e.jb,f)&&a.d(b,"Function")&&(d.plugins=d.plugins||{},d.J=d.J||{},d.plugins[f]=b,d.D=d.D||[],b=d.D.slice(),f&&b.length&&b[0][1]===f))for(var k=0,A=b.length;k<
A;k++){var z=b[k][2]||{};if(d.plugins[f]&&!d.J[f])d.J[f]=new d.plugins[f](z),d.D.shift();else break}}},_requirePlugin:function(b){if(1<b.length){var d=window._hmt,f=b[1],k=b[2]||{};if(a.I(e.jb,f))if(d.plugins=d.plugins||{},d.J=d.J||{},d.plugins[f]&&!d.J[f])d.J[f]=new d.plugins[f](k);else{d.D=d.D||[];for(var k=0,A=d.D.length;k<A;k++)if(d.D[k][1]===f)return;d.D.push(b);n._require([v,e.vc+f+".js"])}}},_trackCustomEvent:function(b){if(1<b.length){var d=b[1];b=b[2];a.d(b,"Object")||(b={});b._iden=d;r.setProperty("customEvent",
b);h.c.b.et=7;h.c.b.ep="";h.c.b.p=t(r.z("customEvent"));h.c.i();h.c.b.p="";r.o("customEvent")}}};n.init();h.Cb=n;return h.Cb})();(function(){var b=h.w;c.spa!==s&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),b.e("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=u,this.b={},this.cb=this.bb=u,this.X=l.X,this.Sa=e.C(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.Ha=x,this.init())}var d=mt.url,a=mt.qb,p=mt.Ma,e=mt.lang,k=mt.cookie,f=mt.f,m=mt.sessionStorage,q=mt.A,r=mt.event,t=h.za,n=h.N,g=n.K,l=h.B,y=h.load,w=h.w;b.prototype={Y:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},pa:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},na:function(a){for(var b=0;b<c.dm.length;b++)if(-1<c.dm[b].indexOf("/")){if(this.pa(a,c.dm[b]))return u}else{var e=d.O(a);if(e&&this.Y(e,c.dm[b]))return u}return x},T:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.Y(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ka:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.pa(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},dc:function(){if(!document.referrer)return l.L-l.P>c.vdur?1:4;var a=x;this.na(document.referrer)&&this.na(document.location.href)?a=u:(a=d.O(document.referrer),a=this.Y(a||"",document.location.hostname));return a?l.L-l.P>c.vdur?1:4:3},Dc:function(){var a,b,d,e,f,g;l.P=t.getData("Hm_lpvt_"+c.id)||0;13===l.P.length&&(l.P=Math.round(l.P/1E3));b=this.dc();a=4!==b?1:0;if(g=t.getData("Hm_lvt_"+c.id)){e=g.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<l.L-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(l.L);4<e.length;)e.shift();g=e.join(",");e=e[e.length-1]}else g=l.L,e="",f=1;this.rc()?(t.setData("Hm_lvt_"+c.id,g,c.age),t.setData("Hm_lpvt_"+c.id,l.L),d=k.tc(this.T(),this.ka())):this.Ob();if(0===c.nv&&this.na(document.location.href)&&(""===document.referrer||this.na(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},rc:function(){var a=d.O(document.location.href);return!e.I("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),
a)},Ob:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&t.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&t.removeData(d[0])}},ob:function(){for(var a=[],b=this.b.et,d=0,e=l.rb.length;d<e;d++){var f=l.rb[d],g=this.b[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}return a.join("&")},Ec:function(){this.Dc();
this.b.si=c.id;this.b.sn=this.Ya();this.b.su=document.referrer;this.b.ds=f.yc;this.b.cl=f.colorDepth+"-bit";this.b.ln=String(f.language).toLowerCase();this.b.ja=f.javaEnabled?1:0;this.b.ck=f.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=p.fc();this.b.v="1.2.82";this.b.cv=decodeURIComponent(t.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=f.H();var a=document.location.href;this.b.cm=d.m(a,l.kc)||"";this.b.cp=d.m(a,l.lc)||d.m(a,l.Jc)||"";this.b.cw=d.m(a,l.jc)||
d.m(a,l.Lc)||"";this.b.ci=d.m(a,l.hc)||d.m(a,l.Ic)||"";this.b.cf=d.m(a,l.mc)||d.m(a,l.Kc)||"";this.b.cu=d.m(a,l.ic)||d.m(a,l.Hc)||"";/https?:/.test(document.location.protocol)&&(this.b.u=a)},init:function(){try{this.Ec(),0===this.b.nv?this.Cc():this.Ua(),h.c=this,this.Eb(),this.Db(),w.M("pv-b"),this.Ac()}catch(b){var d=[];d.push("si="+c.id);d.push("n="+encodeURIComponent(b.name));d.push("m="+encodeURIComponent(b.message));d.push("r="+encodeURIComponent(document.referrer));a.log(l.qa+"//"+l.La+"?"+
d.join("&"))}},Ac:function(){function a(){w.M("pv-d")}this.bb?(this.Ha=u,this.b.et=0,this.b.ep="",this.b.p=g(n.z("pageview")),this.b.vl=f.H(),this.i(a),this.b.p=""):a();this.Z=+new Date;n.o("pageview")},i:function(b){if(this.cb){var d=this;d.b.rnd=Math.round(Math.random()*l.ba);d.b.r=f.orientation;d.b.ww=f.ub;w.M("stag-b");var g=l.qa+"//"+l.La+"?"+d.ob();w.M("stag-d");d.Ab(g);a.log(g,function(a){d.mb(a);e.d(b,"Function")&&b.call(d)})}},Eb:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),
e=d.O(document.referrer)===l.tb?1:0,f=d.m(a,"jn"),g=/^select$/.test(f);a&&(b.test(a)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*l.ba),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",l.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,f))},Db:function(){try{if(window.postMessage&&window.self!==window.parent){var a=this;r.e(window,"message",function(b){if(d.O(b.origin)===
l.tb){b=b.data||{};var e=b.jn||"",f=/^customevent$|^heatmap$|^pageclick$/.test(e);if(RegExp(c.id).test(b.sd||"")&&f)a.b.rnd=Math.round(Math.random()*l.ba),y(l.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}}catch(b){}},Ab:function(a){var b;try{b=q.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);m.set("Hm_unsent_"+
c.id,q.stringify(b))},mb:function(a){var b;try{b=q.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?m.set("Hm_unsent_"+c.id,q.stringify(b)):this.Ua()}},Ua:function(){m.remove("Hm_unsent_"+c.id)},Cc:function(){var b=this,d;try{d=q.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(e){d=[]}if(d.length)for(var f=function(d){a.log(l.qa+"//"+d,function(a){b.mb(a)})},
g=0;g<d.length;g++)f(d[g])},Ya:function(){return Math.round(+new Date/1E3)%65535}};return new b})();var B=h.B,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.f,d=mt.lang,a=mt.event,p=mt.A;if("undefined"!==typeof h.c&&(c.med||(!b.ma||7<b.Xb())&&c.cvcc)){var e,k,f,m,q=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},r=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===x)return x},t=function(a,b){var g={};g.n=e;g.t="clk";g.v=a;if(b){var k=b.getAttribute("href"),l=b.getAttribute("onclick")?""+b.getAttribute("onclick"):v,m=b.getAttribute("id")||"";f.test(k)?(g.sn=
"mediate",g.snv=k):d.d(l,"String")&&f.test(l)&&(g.sn="wrap",g.snv=l);g.id=m}h.c.b.et=86;h.c.b.ep=p.stringify(g);h.c.i();for(g=+new Date;400>=+new Date-g;);};if(c.med)k="/zoosnet",e="swt",f=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,m={click:function(){for(var a=[],b=q(document.getElementsByTagName("a")),b=[].concat.apply(b,q(document.getElementsByTagName("area"))),b=[].concat.apply(b,q(document.getElementsByTagName("img"))),d,e,g=0,k=b.length;g<k;g++)d=b[g],e=
d.getAttribute("onclick"),d=d.getAttribute("href"),(f.test(e)||f.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){k="/other-comm";e="other";f=c.cvcc.q||s;var n=c.cvcc.id||s;m={click:function(){for(var a=[],b=q(document.getElementsByTagName("a")),b=[].concat.apply(b,q(document.getElementsByTagName("area"))),b=[].concat.apply(b,q(document.getElementsByTagName("img"))),d,e,g,k=0,l=b.length;k<l;k++)d=b[k],f!==s?(e=d.getAttribute("onclick"),g=d.getAttribute("href"),n?(d=d.getAttribute("id"),(f.test(e)||
f.test(g)||n.test(d))&&a.push(b[k])):(f.test(e)||f.test(g))&&a.push(b[k])):n!==s&&(d=d.getAttribute("id"),n.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof m&&"undefined"!==typeof f){var g;k+=/\/$/.test(k)?"":"/";var l=function(a,b){if(g===b)return t(k+a,b),x;if(d.d(b,"Array")||d.d(b,"NodeList"))for(var e=0,f=b.length;e<f;e++)if(g===b[e])return t(k+a+"/"+(e+1),b[e]),x};a.e(document,"mousedown",function(a){a=a||window.event;g=a.target||a.srcElement;var b={};for(r(m,function(a,e){b[a]=d.d(e,
"Function")?e():document.getElementById(e)});g&&g!==document&&r(b,l)!==x;)g=g.parentNode})}}})();(function(){var b=mt.g,d=mt.lang,a=mt.event,p=mt.A;if("undefined"!==typeof h.c&&d.d(c.cvcf,"Array")&&0<c.cvcf.length){var e={xb:function(){for(var d=c.cvcf.length,f,m=0;m<d;m++)(f=b.Va(decodeURIComponent(c.cvcf[m])))&&a.e(f,"click",e.Ba())},Ba:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=p.stringify(a);h.c.i()}}};b.lb(function(){e.xb()})}})();
(function(){var b=mt.event,d=mt.A;if(c.med&&"undefined"!==typeof h.c){var a={n:"anti",sb:0,kb:0,clk:0},p=function(){h.c.b.et=86;h.c.b.ep=d.stringify(a);h.c.i()};b.e(document,"click",function(){a.clk++});b.e(document,"keyup",function(){a.kb=1});b.e(window,"scroll",function(){a.sb++});b.e(window,"load",function(){setTimeout(p,5E3)})}})();c.oc!==s&&"1"===String(c.oc)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","OcpcCbHm"]));})();
